FROM mooxe/oraclejdk

MAINTAINER FooTearth "footearth@gmail.com"

WORKDIR /root

# RUN bash -lc "sdk offline"
RUN bash -lc "sdk install maven 3.5.0"
RUN bash -lc "sdk install groovy 2.5.0-beta-1"
RUN bash -lc "sdk install gradle 4.1-rc-1"
RUN bash -lc "sdk install kotlin 1.1.3-2"
RUN bash -lc "sdk install kscript 1.5.3"
