FROM mooxe/openjdk

MAINTAINER FooTearth "footearth@gmail.com"

WORKDIR /root

RUN bash -lc "sdk install maven 3.5.0"
RUN bash -lc "sdk install groovy 2.5.0-beta-1"
RUN bash -lc "sdk install gradle 4.0-rc-2"
RUN bash -lc "sdk install kotlin 1.1.2-2"
