FROM mooxe/oraclejdk

MAINTAINER FooTearth "footearth@gmail.com"

WORKDIR /root

# RUN bash -lc "sdk offline"
RUN bash -lc "sdk install maven 3.5.0"
RUN bash -lc "sdk install groovy 2.6.0-alpha-1"
RUN bash -lc "sdk install gradle 4.2-rc-2"
RUN bash -lc "sdk install kotlin 1.1.51"
RUN bash -lc "sdk install kscript 1.6.0"
